### ISSUE TITLE
random sub sample

### ISSUE THREAD

**Issue by quynhneo** [agude/agude.github.io#55]
Thanks for the great exercise Alex! i.e. https://github.com/agude/agude.github.io/blob/master/files/interview-prep/Interview%20Prep%20Python.ipynb. It's indeed very RAM-consuming, my computer can't handle the whole db but a small portion of it. This is not really an issue but when we randomly sub sample `collisions` and `parties`, many of the `case_id` don't match, thus a lot of rows in one table is not relevant to that in the other. I wonder if it's better to randomly sample one table, and use `case_id` to select the other...

**Comment by agude** [comment]
Glad you liked it!

Yes, I think that would be a better way to do it. Do you want to try to modify the notebook and send a pull request? Happy to review and iterate.

**Comment by quynhneo** [comment]
Thanks, please see the PRs!

**Comment by agude** [comment]
This is closed by #56.
